module.exports = `## Closing Issue 

---

###### This comment was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on the deletion of a \`{{ keyword }}\` comment in {{ sha }}.{{ assignedToString }}`
