module.exports = `## {{ title }}

{{#if body}}
{{ body }}

---

{{/if}}
{{#if range}}
https://{{ githubHost }}/{{ owner }}/{{ repo }}/blob/{{ sha }}/{{ escapedFilename }}#{{ range }}

---

{{/if}}
###### This comment was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a \`{{ keyword }}\` comment in {{ sha }}.{{ assignedToString }}`
