export default `{{#if body}}
{{ body }}

---

{{/if}}
{{#if range}}
https://{{ githubHost }}/{{ owner }}/{{ repo }}/blob/{{ sha }}/{{ escapedFilename }}#{{ range }}

---

{{/if}}
###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a \`{{ keyword }}\` comment in {{ sha }} when #{{ number }} was merged.{{ assignedToString }}`;
