namespace TodoIssue.Core;

public sealed class TemplateRenderer(TodoRunContext context)
{
    public string Issue(TodoItem todo) =>
        Helpers.LineBreak(WithBodyAndRange(todo) +
            $"###### This issue was generated by [todo-issue](https://github.com/Juulsn/todo-issue) based on a `{todo.Keyword}` comment in {todo.Sha}.{todo.AssignedToString}");

    public string Comment(TodoItem todo) =>
        Helpers.LineBreak($"## {todo.Title}\n\n" +
            WithBodyAndRange(todo) +
            $"###### This comment was generated by [todo-issue](https://github.com/Juulsn/todo-issue) based on a `{todo.Keyword}` comment in {todo.Sha}.{todo.AssignedToString}");

    public string Close(TodoItem todo) =>
        $"## Closing Issue \n\n###### This comment was generated by [todo-issue](https://github.com/Juulsn/todo-issue) based on the deletion of a `{todo.Keyword}` comment in {todo.Sha}.";

    private string WithBodyAndRange(TodoItem todo)
    {
        var result = "";
        if (!string.IsNullOrEmpty(todo.BodyComment))
        {
            result += $"{todo.BodyComment}\n\n---\n\n";
        }

        if (!string.IsNullOrEmpty(todo.Range))
        {
            result += $"https://{context.GitHubHost}/{context.Owner}/{context.Repo}/blob/{todo.Sha}/{todo.EscapedFilename}#{todo.Range}\n\n---\n\n";
        }

        return result;
    }
}
