using TodoIssue.Core;

namespace TodoIssue.Tests;

public sealed class TemplateTests
{
    [Fact]
    public void IssueTemplateMatchesOriginalShape()
    {
        var context = new TodoRunContext { Owner = "Juulsn", Repo = "todo-issue", Sha = "SHA", Workspace = "." };
        var renderer = new TemplateRenderer(context);

        var body = renderer.Issue(new TodoItem
        {
            BodyComment = "Test Comment",
            EscapedFilename = Helpers.EscapeFilenameForUrl("some file.txt"),
            Filename = "some file.txt",
            Keyword = "TODO",
            AssignedToString = "@Juulsn",
            Sha = "SHA",
            Range = "L1"
        });

        Assert.Equal(
            "Test Comment\n\n---\n\n" +
            "https://github.com/Juulsn/todo-issue/blob/SHA/some%20file.txt#L1\n\n---\n\n" +
            "###### This issue was generated by [todo-issue](https://github.com/Juulsn/todo-issue) based on a `TODO` comment in SHA.@Juulsn",
            body);
    }
}
